Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/07/2023
Var
   mes: inteiro


Inicio

   mes <- 5

   escolha mes
   caso 1
      escreva ("Janeiro")
   caso 2
      escreva("Fevereiro")
   outrocaso
      escreva ("Outro mês")
   fimescolha


Fimalgoritmo