Algoritmo "semnome"

Var

   inicial, final, contador, quantidade: inteiro

Inicio

   escreval ("Digite o número inicial: ")
   leia (inicial)
   escreval ("Digite o número final: ")
   leia (final)

   quantidade <- 0
   contador <- contador + 1

   enquanto contador < final faca
      quantidade <- quantidade + 1

      contador <- contador + 1
   fimenquanto

   Escreva ("A quantidade de números entre ", inicial, " e ", final, " é: ", quantidade)


Fimalgoritmo