Algoritmo "semnome"

Var
   cod: inteiro

Inicio

   Escreval ("Digite o código de um produto: ")
   Escreval ("01 - Guitarra, 02 - Amplificador, 03 - Pedaleira")

   leia (cod)

   escolha cod

   caso 01
      escreval ("Guitarra")
   caso 02
      escreval ("Amplificador")
   caso 03
      escreval ("Pedaleira")
   outrocaso
      escreval ("Escolha novamente, código errado!")

   fimescolha


Fimalgoritmo